CREATE USER `api`@`%`;
GRANT INSERT,SELECT,DELETE ON `civ_api`.* TO `api`@`%`;

CREATE DATABASE IF NOT EXISTS `civ_api`;

CREATE TABLE IF NOT EXISTS `civ_api`.`twimg_data` (
	`ID`		INT			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TwiID`		VARCHAR(15)	NOT NULL,
	`FileName`	VARCHAR(63)	NOT NULL,
	`CreatedAt`	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP
);
