version: '3.3'

services:
    nginx:
        image: "nginx"
        container_name: civ_web_test
        ports:
            - "80:80"
        volumes:
            - ./WEB_SERVER/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./WEB_SERVER/www/html:/var/www/html
            - ./IMAGE:/var/www/html/civ.zerono.server-on.net/IMAGE
        environment:
            TZ: 'Asia/Tokyo'
            NGINX_PORT: 80
        networks:
            - proxy
        restart: always
        depends_on:
            - db
            - api
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    api:
        build: ./API_SERVER
        ports:
            - "$API_SERVER_PORT"
        container_name: civ_api
        volumes:
            - ./IMAGE:/go/Content
        environment:
            MYSQL_DB: $MYSQL_DB
            MYSQL_TABLE: $MYSQL_TABLE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PORT: $MYSQL_SERVER_PORT
            TZ: 'Asia/Tokyo'
        networks:
            - proxy
            - backend
        restart: always
        depends_on:
            - db

    db:
        build: ./DB_SERVER
        container_name: civ_db
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
            TZ: 'Asia/Tokyo'
        networks:
            - backend
        restart: always

volumes:
    db:

networks:
    proxy:
    backend:

