version: '3'

services:
    api:
        build: ./API
        ports:
            - "5300:5300"
        container_name: img_v_api_zero
        environment:
            -
        depends_on:
            - db

    db:
        build: ./DB
        container_name: img_v_db_zero
        expose:
            - '3306'
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            TZ: 'Asia/Tokyo'
        restart: always
volumes:
    db:
