version: '3'

services:
    api:
        build: ./API_SERVER
        ports:
            - "$API_SERVER_PORT"
        container_name: img_v_api_zero
        environment:
            MYSQL_DB: $MYSQL_DB
            MYSQL_USER: $MYSQL_USER
            MYSQL_PORT: $MYSQL_SERVER_PORT
        restart: always
        depends_on:
            - db

    db:
        build: ./DB_SERVER
        container_name: img_v_db_zero
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
            TZ: 'Asia/Tokyo'
        restart: always
volumes:
    db:
