version: '3.3'

services:
    web:
        image: "nginx"
        container_name: civ_web
        ports:
            - "5280:5280"
        volumes:
            - ./WEB_SERVER/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./WEB_SERVER/www/html:/var/www/html
            - ./WEB_SERVER/zerono.cloud.pem:/etc/ssl/zerono.cloud.pem
            - ./WEB_SERVER/zerono.cloud.key:/etc/ssl/zerono.cloud.key
            - ./IMAGE:/var/www/html/civ.zerono.cloud/IMAGE
        environment:
            TZ: 'Asia/Tokyo'
            NGINX_PORT: 5280
        networks:
            - nginx_reverse_proxy
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    api:
        build: ./API_SERVER
        container_name: civ_api
        ports:
            - "$API_SERVER_PORT"
        volumes:
            - ./IMAGE:/go/Content
        environment:
            MYSQL_DB: $MYSQL_DB
            MYSQL_TABLE: $MYSQL_TABLE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PORT: $MYSQL_SERVER_PORT
            TZ: 'Asia/Tokyo'
        networks:
            - nginx_reverse_proxy
            - backend
        restart: always
        depends_on:
            - db

    db:
        build: ./DB_SERVER
        container_name: civ_db
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
            TZ: 'Asia/Tokyo'
        networks:
            - backend
        restart: always

volumes:
    db:

networks:
    nginx_reverse_proxy:
        external: true
    backend:
