version: '3.3'

services:
    api:
        build: ./API_SERVER
        ports:
            - "$API_SERVER_PORT"
        container_name: civ_api
        volumes:
            - ./NGINX/IMAGE:/go/Content
        environment:
            MYSQL_DB: $MYSQL_DB
            MYSQL_TABLE: $MYSQL_TABLE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PORT: $MYSQL_SERVER_PORT
            TZ: 'Asia/Tokyo'
        networks:
            - nginx_reverse_proxy
            - backend
        restart: always
        depends_on:
            - db

    db:
        build: ./DB_SERVER
        container_name: civ_db
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
            TZ: 'Asia/Tokyo'
        networks:
            - backend
        restart: always

volumes:
    db:

networks:
    nginx_reverse_proxy:
        external: true
    backend:

