version: '3'

services:
    nginx:
        image: "nginx"
        container_name: civ_web_test
        ports:
            - "80:80"
        volumes:
            - ./WEB_SERVER/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./WEB_SERVER/www/html:/var/www/html
        environment:
            - NGINX_PORT=80
        restart: always
        depends_on:
            - db
            - api
        networks:
            - nginx_reverse_proxy

    api:
        build: ./API_SERVER
        ports:
            - "$API_SERVER_PORT"
        container_name: civ_api
        environment:
            MYSQL_DB: $MYSQL_DB
            MYSQL_TABLE: $MYSQL_TABLE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PORT: $MYSQL_SERVER_PORT
        restart: always
        depends_on:
            - db
        networks:
            - nginx_reverse_proxy

    db:
        build: ./DB_SERVER
        container_name: civ_db
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
            TZ: 'Asia/Tokyo'
        restart: always
        networks:
            - nginx_reverse_proxy

volumes:
    db:

networks:
    nginx_reverse_proxy:
        external: true

