version: '3.3'

services:
    nginx:
        image: "nginx"
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./WEB_SERVER/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./WEB_SERVER/www/html:/var/www/html
            - ./IMAGE:/var/www/html/civ.zerono.cloud/IMAGE
        environment:
            TZ: 'Asia/Tokyo'
            NGINX_PORT: 80
        networks:
            - nginx_reverse_proxy
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "10"

networks:
    nginx_reverse_proxy:
        external: true

